services:
  server:
    build: .
    container_name: concurrent-http-server
    ports:
      - "8080:8080"
    volumes:
      - ../Lab1/content:/app/content:ro
    command: ["python", "server.py", "content", "--host", "0.0.0.0", "--port", "8080", "--workers", "8", "--simulate-delay", "1.0"]
  loadtest:
    build: .
    entrypoint: ["python", "load_test.py"]
    profiles: ["loadtest"]
    working_dir: /app
    depends_on:
      - server
